### PR TITLE
Feature/flexi cell examples

### PR DESCRIPTION
**Pull request by kenjishiromajp**

### CODE REVIEW

**Comment by samithaf** [comment]
@KateMacdonald @kenjishiromajp are you happy with this change?

**Comment by KateMacdonald** [comment]
@samithaf I was going to get Hannah to do some work on this too.

**Comment by samithaf** [comment]
> @samithaf I was going to get Hannah to do some work on this too.

@HZ991 are you still working on this?

**Comment by HZ991** [comment]
Will begin to work on this

**Review by jaortiz — APPROVED** [review]

**Pull request merged**
